% Postprocessing script for analog-to-digital converter example 2.

% Create HybridArc objects.
sol = HybridArc(t, j, x); %#ok<IJCL> (suppress a warning about 'j)
sol1 = HybridArc(t1, j1, x1);

% Plot solution
clf
pb = HybridPlotBuilder()...
    .subplots('on')...
    .legend('Ball position', 'Ball velocity')...
    .slice([1 2])...
    .flowColor('green')...
    .plotFlows(sol1);
hold on
pb.legend('ADC output', 'ADC output')...
    .slice([1 2])...
    .flowColor('blue')...
    .plotFlows(sol);
 