toolbox_dirs = ["CommonFiles/lite", ...
    "CommonFiles/lite/examples", ...
    "CommonFiles/plottingFunctions", ...
    "CommonFiles/simulinkBased/Library2014b"];
dev_dirs = ["doc", "CommonFiles/lite/tests", ...
            "helpFiles/Matlab_Publish/MatlabScripts/v3.0"];

% Setup path
for d = [toolbox_dirs, dev_dirs]
    addpath(d) 
end