import hybrid.examples.*
config = HybridSolverConfig('Refine', 8); % 'Refine' option makes the plots smoother.
system = BouncingBall();
sol    = system.solve([10, 0], [0 30], [0 30], config).select(1).restrictJ([0 13]);
hpb = HybridPlotBuilder().legend("Bouncing Ball").title('Jump Times').jumpMarker('s');
hpb.setAxesArgs("XTick", sol.jump_times, ...
    "XTickLabel", {"$t_1$", "$t_2$", "$t_3$", "$t_4$", "$t_5$", "$t_6$", "$t_7$", "$t_8$", "$t_9$", "$t_{10}$", "$t_{11}$", "$t_{12}$", "$t_{13}$"},...
    'XTickLabelRotation', 0, ...
    'TickDir', 'both', ...
    'TickLength', [0.01, 0.5])
hpb.setPlotJumpArgs('MarkerFaceColor', 'red')
hpb.plotFlows(sol)