import hybrid.examples.*
disp('hello')

config = HybridSolverConfig('Refine', 8); % 'Refine' option makes the plots smoother.
system = BouncingBall();
sol    = system.solve([10, 0], [0 30], [0 30], config).restrictJ([0 13]);


%%
hpb = HybridPlotBuilder().legend("Bouncing Ball").title('Jump Times').jumpMarker('s');
% hpb.setAxesArgs("XTick", sol.jump_times, ...
%     "XTickLabel", {"$t_1$", "$t_2$", "$t_3$", "$t_4$", "$t_5$", "$t_6$", "$t_7$", "$t_8$", "$t_9$", "$t_{10}$", "$t_{11}$", "$t_{12}$", "$t_{13}$"},...
%     'XTickLabelRotation', 0, ...
%     'TickDir', 'both', ...
%     'TickLength', [0.01, 0.5])


%%
hpb.setAxesArgs(...
    'FontSmoothing', 'off', ...
    'XTick', [5, 7, 12], ...
    'XTickLabel', ["A", "B", "C"], ...
    'XTickLabelRotation', 45, ...
    'TickDir', 'both', ...
    'TickLength', [0.01, 0.1], ... % 1st entry: 2D Tick length. 2nd entry: 3D Tick length
    'YLim', [-20, 20], ...
    'XLim', [0.2, 7], ...
    'XAxisLocation', 'origin', ...
    'YAxisLocation', 'origin', ...
    'YDir', 'reverse', ... % Flip the vertical direction.
    'XGrid', 'on', ... 
    'YGrid', 'on', ... 
    'Layer', 'top', ... % Placement of grid lines and tick marks
    'GridLineStyle', '--', ...
    'GridLineWidth', 2, ... % Since R2023a
    'GridColor', [0, 0.4, 0.7], ... % Since R2023a
    'GridAlpha', 0.6, ...
    'XMinorGrid', 'on', ...
    'MinorGridLineStyle', ':', ...
    'MinorGridLineWidth', 1, ...
    'Position', [0.1, 0.2, 0.8, 0.6], ... % Set the boundearies of the axes.
    'TitleHorizontalAlignment', "left", ...  
    'Color', [0.9, 0.9, 1], ... % Background color
    'LineWidth', 1, ... Box boundary line width
    'Box', 'off', ... % Boundary box
    'Clipping', 'off' ... % Clip plots to the 
    )
% hpb.setAxesArgs('OuterPosition', [0.1, 0, 0.8, 0.5]);
% hpb.setAxesArgs('XScale', 'log')
hpb.plotPhase(sol)
subtitle('Hello')


hpb.setAxesArgs(...
    'BoxStyle', 'full', ... % Draw full box in 3D, 
    'ClippingStyle', 'rectangle', ...
    'View', [45 45], ... % [azimuth elevation]
    'Projection', 'perspective' ...
    )
