% Project: Simulation of a hybrid system (Finite state machine)
% Description: initialization FSM


sol = HybridArc(t, j, x);

figure(1)
HybridPlotBuilder().subplots('on')...
    .labels('$q_{1}$', '$q_{2}$')...
    .legend('$q_{1}$', '$q_{2}$')...
    .plotFlows(sol)

figure(2)
HybridPlotBuilder().subplots('on')...
    .labels('$q_{1}$', '$q_{2}$')...
    .legend('$q_{1}$', '$q_{2}$')...
    .plotJumps(sol)

figure(3)
HybridPlotBuilder().subplots('on')...
    .legend('$q_{1}$')...
    .plotHybrid(sol.slice(1))     
grid on
view(37.5, 30) 


